max_epochs: 
max_steps: 500
devices: 1
accumulate_grad_batches: 1
amp: true
log_every_n_steps: 10
limit_train_batches: 1.0
limit_val_batches: 1.0
check_val_every_n_epoch: 
val_check_interval: 100
resume_from_checkpoint:
